app:
  base-url: ${APP_BASE_URL:http://localhost:8080}

google:
  maps:
    api-key: ${GOOGLE_MAPS_API_KEY}

liteapi:
  key: ${LiteAPI_API_KEY}
  base-url: https://api.liteapi.travel
  book-base-url: https://book.liteapi.travel

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}

spring:
  application:
    name: api
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SUPPORT_EMAIL}
    password: ${APP_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  jackson:
    default-property-inclusion: non_null

  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        model: claude-opus-4-7
        max-tokens: 4096

logging:
  level:
    com.abdullah.api: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.web: INFO

server:
  error:
    include-message: always
    include-stacktrace: always