### Shortest flight from Islamabad (ISB) to London (LHR) on 1st July 2026 with no stops, for 1 adult, in USD currency.
# curl --request POST
#     --url https://api.liteapi.travel/v3.0/flights/rates
#     --header 'X-API-Key: sand_ce497649-551d-4c4b-9ba3-632b0e5d4953'
#     --header 'accept: application/json'
#     --header 'content-type: application/json'
#     --data '
#{
#  "legs": [
#    {
#      "origin": "ISB",
#      "destination": "LHR",
#      "date": "2026-07-01",
#      "direction": "OUTBOUND"
#    }
#  ],
#  "adults": 1,
#  "children": 0,
#  "infants": 0,
#  "maxStops": 0,
#  "currency": "USD",
#  "filters": {
#    "maxStops": 0
#  }
#}
#'
POST https://api.liteapi.travel/v3.0/flights/rates
X-API-Key: sand_ce497649-551d-4c4b-9ba3-632b0e5d4953
accept: application/json
Content-Type: application/json


{
  "legs": [
    {
      "origin": "ISB",
      "destination": "LHR",
      "date": "2026-07-01",
      "direction": "OUTBOUND"
    }
  ],
  "adults": 1,
  "children": 0,
  "infants": 0,
  "maxStops": 0,
  "currency": "USD",
  "filters": {
    "maxStops": 0
  }
}


###
### Multi-leg based flight

# curl --request POST
#     --url https://api.liteapi.travel/v3.0/flights/rates
#     --header 'X-API-Key: sand_ce497649-551d-4c4b-9ba3-632b0e5d4953'
#     --header 'accept: application/json'
#     --header 'content-type: application/json'
#     --data '
#{
#  "legs": [
#    {
#      "origin": "ISB",
#      "destination": "LHR",
#      "date": "2026-07-01",
#      "direction": "OUTBOUND"
#    },
#    {
#      "origin": "LHR",
#      "destination": "AQJ",
#      "date": "2026-07-05",
#      "direction": "OUTBOUND"
#    },
#    {
#      "origin": "AQJ",
#      "destination": "ISB",
#      "date": "2026-07-12",
#      "direction": "OUTBOUND"
#    }
#  ],
#  "adults": 1,
#  "children": 0,
#  "infants": 0,
#  "maxStops": 0,
#  "currency": "USD",
#  "cabinClass": "BUSINESS",
#  "filters": {
#    "maxStops": 0
#  }
#}
#'
POST https://api.liteapi.travel/v3.0/flights/rates
X-API-Key: sand_ce497649-551d-4c4b-9ba3-632b0e5d4953
accept: application/json
Content-Type: application/json

{
  "legs": [
    {
      "origin": "ISB",
      "destination": "LHR",
      "date": "2026-07-01",
      "direction": "OUTBOUND"
    },
    {
      "origin": "LHR",
      "destination": "AQJ",
      "date": "2026-07-05",
      "direction": "OUTBOUND"
    },
    {
      "origin": "AQJ",
      "destination": "ISB",
      "date": "2026-07-12",
      "direction": "OUTBOUND"
    }
  ],
  "adults": 1,
  "children": 0,
  "infants": 0,
  "maxStops": 0,
  "currency": "USD",
  "cabinClass": "ECONOMY",
  "filters": {
    "maxStops": 2
  }
}


###