### Shortest flight from Islamabad (ISB) to London (LHR) on 1st July 2026 with no stops, for 1 adult, in USD currency.
# curl --request POST
#     --url https://api.liteapi.travel/v3.0/flights/rates
#     --header 'X-API-Key: sand_ce497649-551d-4c4b-9ba3-632b0e5d4953'
#     --header 'accept: application/json'
#     --header 'content-type: application/json'
#     --data '
#{
#  "legs": [
#    {
#      "origin": "ISB",
#      "destination": "LHR",
#      "date": "2026-07-01",
#      "direction": "OUTBOUND"
#    }
#  ],
#  "adults": 1,
#  "children": 0,
#  "infants": 0,
#  "maxStops": 0,
#  "currency": "USD",
#  "filters": {
#    "maxStops": 0
#  }
#}
#'
POST https://api.liteapi.travel/v3.0/flights/rates
X-API-Key: sand_ce497649-551d-4c4b-9ba3-632b0e5d4953
accept: application/json
Content-Type: application/json


{
  "legs": [
    {
      "origin": "ISB",
      "destination": "LHR",
      "date": "2026-07-01",
      "direction": "OUTBOUND"
    }
  ],
  "adults": 1,
  "children": 0,
  "infants": 0,
  "maxStops": 0,
  "currency": "USD",
  "filters": {
    "maxStops": 0
  }
}


###
### Multi-leg based flight

# curl --request POST
#     --url https://api.liteapi.travel/v3.0/flights/rates
#     --header 'X-API-Key: sand_ce497649-551d-4c4b-9ba3-632b0e5d4953'
#     --header 'accept: application/json'
#     --header 'content-type: application/json'
#     --data '
#{
#  "legs": [
#    {
#      "origin": "ISB",
#      "destination": "LHR",
#      "date": "2026-07-01",
#      "direction": "OUTBOUND"
#    },
#    {
#      "origin": "LHR",
#      "destination": "AQJ",
#      "date": "2026-07-05",
#      "direction": "OUTBOUND"
#    },
#    {
#      "origin": "AQJ",
#      "destination": "ISB",
#      "date": "2026-07-12",
#      "direction": "OUTBOUND"
#    }
#  ],
#  "adults": 1,
#  "children": 0,
#  "infants": 0,
#  "maxStops": 0,
#  "currency": "USD",
#  "cabinClass": "BUSINESS",
#  "filters": {
#    "maxStops": 0
#  }
#}
#'
POST https://api.liteapi.travel/v3.0/flights/rates
X-API-Key: sand_ce497649-551d-4c4b-9ba3-632b0e5d4953
accept: application/json
Content-Type: application/json

{
  "legs": [
    {
      "origin": "ISB",
      "destination": "LHR",
      "date": "2026-07-01",
      "direction": "OUTBOUND"
    },
    {
      "origin": "LHR",
      "destination": "AQJ",
      "date": "2026-07-05",
      "direction": "OUTBOUND"
    },
    {
      "origin": "AQJ",
      "destination": "ISB",
      "date": "2026-07-12",
      "direction": "OUTBOUND"
    }
  ],
  "adults": 1,
  "children": 0,
  "infants": 0,
  "maxStops": 0,
  "currency": "USD",
  "cabinClass": "ECONOMY",
  "filters": {
    "maxStops": 2
  }
}


###


# curl --request POST
#     --url https://api.liteapi.travel/v3.0/hotels/rates
#     --header 'X-API-Key: sand_ce497649-551d-4c4b-9ba3-632b0e5d4953'
#     --header 'accept: application/json'
#     --header 'content-type: application/json'
#     --data '
#{
#  "occupancies": [
#    {
#      "adults": 2
#    }
#  ],
#  "currency": "USD",
#  "guestNationality": "PK",
#  "checkin": "2026-07-01",
#  "checkout": "2026-07-02",
#  "latitude": 34.052235,
#  "longitude": -118.243683,
#  "radius": 5000,
#  "aiSearch": "Romantic getaway with Italian vibes in London near the London Eye",
#  "limit": 3
#}
#'
POST https://api.liteapi.travel/v3.0/hotels/rates
X-API-Key: sand_ce497649-551d-4c4b-9ba3-632b0e5d4953
accept: application/json
Content-Type: application/json


{
  "occupancies": [
    {
      "adults": 2
    }
  ],
  "currency": "USD",
  "guestNationality": "PK",
  "checkin": "2026-07-01",
  "checkout": "2026-07-02",
  "latitude": 34.052235,
  "longitude": -118.243683,
  "radius": 5000,
  "limit": 3,
  "includeHotelData": true
}


###


# curl --request GET
#     --url 'https://api.liteapi.travel/v3.0/data/hotels?limit=10&longitude=-115.16988&latitude=36.1251&radius=10000&minRating=8.6'
#     --header 'X-API-Key: sand_ce497649-551d-4c4b-9ba3-632b0e5d4953'
#     --header 'accept: application/json'
GET https://api.liteapi.travel/v3.0/data/hotels?limit=10&longitude=-115.16988&latitude=36.1251&radius=10000&
    minRating=8.6
X-API-Key: sand_ce497649-551d-4c4b-9ba3-632b0e5d4953
accept: application/json

###